# Generated by Django 6.1.1 on 2026-09-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-timestamp',)},
        ),
    ]
